# basic http headers
request_headers:
  Accept-Encoding: gzip, deflate
  Accept-Language: zh-CN,zh;q=0.9
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

file_path:
  # allure path
  allure_path: allure\bin\allure

# the database for assert your sql result in API test case.
database:
  host: localhost
  port: 3306
  user: guest
  password: '123456'  # this field must be string object
  db_name:  book_demo


# the database that store the API test case
test_case_database:
  host: localhost
  port: 3306
  user: guest
  password: '123456'  # this field must be string object
  db_name:  book_demo

